# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nbacli < Formula
  desc ""
  homepage "https://github.com/dylantientcheu/nbacli"
  version "0.1.2"

  on_macos do
    url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.2/nbacli_0.1.2_macOS_amd64.tar.gz"
    sha256 "7f7cf16979bbb051ff4ccb42e04e28cb6670d109b2cac83eeab9a03ef6e93c2a"

    def install
      bin.install "nbacli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Nbacli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.2/nbacli_0.1.2_linux_amd64.tar.gz"
      sha256 "3352aa69c13380e67892028ff407808038d09a1c98b8c777a9a32104c7d864ea"

      def install
        bin.install "nbacli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.2/nbacli_0.1.2_linux_armv6.tar.gz"
      sha256 "259e9c2a80a2995cd7190b509e491581ad9cbe43ecf9ad1daad536c4c16f64b5"

      def install
        bin.install "nbacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.2/nbacli_0.1.2_linux_arm64.tar.gz"
      sha256 "8f3d61d1d82a8ab0ff64c5293f414a2ba6945eb2efdbb1d4b6d95f9198fcb21e"

      def install
        bin.install "nbacli"
      end
    end
  end
end
