# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nbacli < Formula
  desc ""
  homepage "https://github.com/dylantientcheu/nbacli"
  version "0.1.0"

  on_macos do
    url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.0/nbacli_0.1.0_Darwin_all.tar.gz"
    sha256 "f3085b41a8eaa1aefba3fcb1cb9f1ec315fa9c3f88f0f5cf348faa9b3201e193"

    def install
      bin.install "nbacli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.0/nbacli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "c4035c5eb9d95921ea9fca069d68a3e6406a9f52cfd3869b248f7e18abe3fc39"

      def install
        bin.install "nbacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.0/nbacli_0.1.0_Linux_arm64.tar.gz"
      sha256 "30fc3440332e245b8efa88c829c011c228b3fd9e3a653bfa849e58d0a3d1f122"

      def install
        bin.install "nbacli"
      end
    end
  end
end
