# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nbacli < Formula
  desc ""
  homepage "https://github.com/dylantientcheu/nbacli"
  version "0.1.0"

  on_macos do
    url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.0/nbacli_0.1.0_Darwin_all.tar.gz"
    sha256 "6db238fe6229fc890fbac7432694655b552e759ea7e92b96b7db4de4f6b6e3fc"

    def install
      bin.install "nbacli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.0/nbacli_0.1.0_Linux_arm64.tar.gz"
      sha256 "7717114b1e612aaa6cc964f28d707e7d8fe67b4416b2b47710de936fc34809d6"

      def install
        bin.install "nbacli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dylantientcheu/nbacli/releases/download/v0.1.0/nbacli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "f9aa4979eb9090fe03e53af121b4ac58b8094d7b826a5e15f292257916eba857"

      def install
        bin.install "nbacli"
      end
    end
  end
end
